### ISSUE TITLE
spark源码编译报错： "请使用 -source 7 或更高版本以启用 diamond 运算符"

### ISSUE THREAD

**Issue by LinMingQiang** [gouyangyang/Diagrammatize_Spark#1]
我在用maven编译spark-1.6.3的时候遇到 "请使用 -source 7 或更高版本以启用 diamond 运算符"。但是我确定环境的jdk是1.8 。请教下什么怎么回事。

**Comment by gouyangyang** [comment]
你的错误信息呢。看看你scala 的版本还有jdk的版本是不是对应的，是不是有版本的冲突，






在 2018-12-06 19:23:54，"LinMingQiang" <notifications@github.com> 写道：


我在用maven编译spark-1.6.3的时候遇到 "请使用 -source 7 或更高版本以启用 diamond 运算符"。但是我确定环境的jdk是1.8 。请教下什么怎么回事。

**Comment by LinMingQiang** [comment]
scala 2.10 
jdk 1.8
spark 1.6.3
使用mvn clean package 编译。
出现 "请使用 -source 7 或更高版本以启用 diamond 运算符" 错误。
试了几个同事的电脑都是这个问题。

**Comment by gouyangyang** [comment]
这个就不是很清楚了






在 2018-12-10 16:43:05，"LinMingQiang" <notifications@github.com> 写道：


scala 2.10
jdk 1.8
spark 1.6.3
使用mvn clean package 编译。
出现 "请使用 -source 7 或更高版本以启用 diamond 运算符" 错误。
试了几个同事的电脑都是这个问题。
